
#spring:
#  kafka:
##    bootstrap-servers: localhost:8092 # should match with embedded broker host port
##    producer:
##      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
#    properties:
#      schema.registry.url: localhost:8091
#      auto.register.schemas: false
#      use.latest.version: true
##      json:
##        fail.invalid.schema: true
##        oneof.for.nullables: false
##        write.dates.iso8601: true
server:
  port: 9090
  servlet:
    context-path: /test-kafka